- name: PREPARAR_HOSTS
  hosts: maquinas_virtuales
  become: true
  become_user: root
  tasks:

  # INSTALAR DEPENDENCIAS
    - name: INSTALAR - Repositorio EPEL
      dnf:
        name:
          - epel-release
        state: latest
        update_cache: true

    - name: INSTALAR - Paquetes requeridos
      dnf:
        name:
          - python3-pip
        state: latest
        update_cache: true
  
  # NETWORKING
    - name: CREAR - interfaz Bridge02
      block:
        - name: CREAR - Bridge02
          community.general.nmcli:
            conn_name: bridge02
            state: present
            type: macvlan
            ifname: bridge02
            mode: bridge
            master: enp0s3        
        - name: ASIGNAR - Direccion IP a Bridge02
          community.general.nmcli:
            conn_name: bridge02
            state: present
            ipv4:
              addresses: ['192.168.2.50/24']
        - name: LEVANTAR - Bridge02
          community.general.nmcli:
            conn_name: bridge02
            state: up
        - name: Añadir ruta a la tabla de enrutamiento
          community.general.nmcli:
            conn_name: bridge02
            state: present
            ipv4:
              routes: ['192.168.2.0/24']

    - name: CREAR - interfaz Bridge03
      block:
        - name: CREAR - Bridge03
          community.general.nmcli:
            conn_name: bridge03
            state: present
            type: macvlan
            ifname: bridge03
            mode: bridge
            master: enp0s3        
        - name: ASIGNAR - Direccion IP a Bridge03
          community.general.nmcli:
            conn_name: bridge03
            state: present
            ipv4:
              addresses: ['192.168.3.50/24']
        - name: LEVANTAR - Bridge03
          community.general.nmcli:
            conn_name: bridge03
            state: up
        - name: Añadir ruta a la tabla de enrutamiento
          community.general.nmcli:
            conn_name: bridge03
            state: present
            ipv4:
              routes: ['192.168.3.0/24']

  # DOCKER
    - name: AÑADIR - Clave GPG Docker
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present
    
    - name: AÑADIR - Repositorio Docker
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644

    - name: INSTALAR - Docker CE
      dnf:
        name: docker-ce
        state: present

    - name: INSTALAR - Modulo Docker Python
      pip:
        name: 
        - docker
        - docker-compose

    - name: INICIAR - Servicio Docker
      block:
        - name: Iniciar Docker
          shell: systemctl start docker

    - name: CREAR - Networks Docker
      block:
        - name: CREAR - Bridge02 containers
          community.docker.docker_network:
            name: bridge02
            driver: macvlan
            driver_options:
              parent: bridge02
            ipam_options:
              subnet: 192.168.2.0/24

        - name: CREAR - Bridge03 containers
          community.docker.docker_network:
            name: bridge03
            driver: macvlan
            driver_options:
              parent: bridge03
            ipam_options:
              subnet: 192.168.3.0/24