- name: PREPARAR_HOSTS
  hosts: maquinas_virtuales
  become: true
  become_user: root
  tasks:

  # INSTALAR DEPENDENCIAS
    - name: INSTALAR - Repositorio EPEL
      dnf:
        name:
          - epel-release
        state: latest
        update_cache: true

    - name: INSTALAR - Paquetes requeridos
      dnf:
        name:
          - python3-pip
        state: latest
        update_cache: true
  
  # FIREWALL
    - name: ABRIR - Puerto 3306 para MariaDB
      firewalld:
        port: 3306/tcp
        permanent: yes
        state: enabled

    - name: ABRIR - Puerto 80 para HTTP
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled

    - name: ABRIR - Puerto 8080
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled

  # DOCKER
    - name: AÑADIR - Clave GPG Docker
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present
    
    - name: AÑADIR - Repositorio Docker
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644

    - name: INSTALAR - Docker CE
      dnf:
        name: docker-ce
        state: present

    - name: INSTALAR - Modulo Docker Python
      pip:
        name: 
        - docker
        - docker-compose

    - name: INICIAR - Servicio Docker
      block:
        - name: Iniciar Docker
          shell: systemctl start docker