---
- hosts: maquinas_virtuales
  vars:
  # Nodo inicial + numNodos (MariaDB)
    numNodos: 3
  # Puertos Nodos MariaDB.
    puerto: 10000
  become: true
  tasks:

    - name: COMPROBACION - Eliminar contenedores activos, huerfanos.
      shell: docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && docker-compose down --remove-orphans || true

    - name: COMPROBACION - Eliminar redes antiguas.
      shell: docker network prune -f  || true

    - name: COMPROBACION - Salir de Docker Swarm
      shell: docker swarm leave --force || true

    - name: CREACION - haproxy.cfg  con Jinja2
      template:
        src: /home/ansible/.ansible/templates/jinjaHaproxy.j2
        dest: /home/ansible/haproxy.cfg
        mode: '0777'

    - name: CREACION - docker-compose.yml con Jinja2
      template:
        src: /home/ansible/.ansible/templates/jinjaCompose.j2
        dest: /home/ansible/docker-compose.yml
        mode: '0777'

    - name: INICIAR - Servicio Docker
      systemd:
        name: docker
        state: started

    - name: INICIAR - Contenedores
      docker_compose:
        project_src: /home/ansible
        files: docker-compose.yml
