---
- hosts: maquinas_virtuales
  become: true
  vars_prompt:
    - name: "numNodos"
      prompt: "Introduzca número de nodos"
      private: yes
  tasks:

    - name: COMPROBACION - Eliminar contenedores activos, huerfanos.
      shell: docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && docker-compose down --remove-orphans || true

    - name: COMPROBACION - Eliminar redes antiguas.
      shell:  docker network prune -f  || true

    - name: COMPROBACION - Eliminar volumenes antiguos.
      docker_volume:
        name: mariadb
        state: absent

    - name: COMPROBACION - Salir de Docker Swarm
      shell: docker swarm leave --force || true
      
    - name: COPIAR - Configuración de HAProxy
      copy:
        src: /home/ansible/haproxy.cfg
        dest: /home/ansible/haproxy.cfg
      
    - name: COPIAR - Docker-Compose
      copy:
        src: /home/ansible/docker/docker-compose.yml
        dest: /home/ansible/docker-compose.yml
    
    - name: COPIAR - Bash scripting
      copy:
        src: /home/ansible/scripts/mariadbnode.sh
        dest: /home/ansible/mariadbnode.sh
        
    - name: INICIAR - Bootstrap MariaDB Galera Cluster
      shell: |
        docker run -d --name mariadb-galera-0 
        -e MARIADB_GALERA_CLUSTER_NAME=galeraASIR 
        -e ALLOW_EMPTY_PASSWORD=yes 
        -e MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes 
        -e MARIADB_USER=my_user 
        -e MARIADB_DATABASE=matias
        bitnami/mariadb-galera:latest

    - name: INICIAR - Nodos MariaDB Galera Cluster
      shell: |
        for i in $(seq 1 {{ numNodos }}); do
          docker run -d --name mariadb-galera-$i --link mariadb-galera-0:mariadb-galera 
            -e MARIADB_GALERA_CLUSTER_NAME=galeraASIR 
            -e MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera:4567,0.0.0.0:4567 
            bitnami/mariadb-galera:latest
        done
