---
- hosts: maquinas_virtuales
  vars:
  # Nodo inicial + numNodos (MariaDB)
    numNodos: 3
    puerto: 10000
  become: true
  tasks:

    - name: CREACION - haproxy.cfg  con Jinja2
      template:
        src: /home/ansible/.ansible/templates/jinjaHaproxy.j2
        dest: /home/ansible/haproxy.cfg
        mode: '0644'
